data({
  datas: [
    {
      regiao: "Sudeste",
      estado: "Minas Gerais",
      nome: "Belo Horizonte",
      local: "Shopping Ponteio",
      endereco: "BR-356, 2500",
      observacao: "Clube",
      coordenadas: {
        longitude: -19.963207,
        latitude: -43.940267,
      },
    },
    {
      regiao: "Sudeste",
      estado: "Minas Gerais",
      nome: "Tiradentes",
      local: "Pousada Pequena Tiradentes",
      endereco: "Av. Gov. Israel Pinheiro, 670",
      observacao: "Hotel",
        rota: "https://www.google.com/maps/dir//Av.+Gov.+Israel+Pinheiro,+670,+Tiradentes+-+MG,+36325-000/@-21.1280198,-44.1733059,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0xa1c0b2df29634f:0x20c575ff95a4142e!2m2!1d-44.1711172!2d-21.1280248",  
      coordenadas: {
        longitude: -21.127335,
        latitude: -44.171995,
      },
          
    },
    {
      regiao: "Sudeste",
      estado: "Rio de Janeiro",
      nome: "Búzios",
      local: "Casas Branca Hotel & SPA",
      endereco: "R. Morro do Humaitá, 10",
      observacao: "Hotel",
      coordenadas: {
        longitude: -22.751956,
        latitude: -41.883627,
      },
    },
    {
      regiao: "Sudeste",
      estado: "Rio de Janeiro",
      nome: "Rio de Janeiro",
      local: "Campo Olímpico de Golfe",
      endereco: "Av. Gen. Moisés Castelo Branco Filho, 700",
      observacao: "Clube",
      coordenadas: {
        longitude: -23.003805,
        latitude: -43.40044,
      },
    },
    {
      regiao: "Sudeste",
      estado: "Rio de Janeiro",
      nome: "Rio de Janeiro",
      local: "Iate Clube Rio de Janeiro",
      endereco: "Av. Pasteur, 333",
      observacao: "Clube",
      coordenadas: {
        longitude: -22.951303,
        latitude: -43.173217,
      },
    },
    {
      regiao: "Sudeste",
      estado: "São Paulo",
      nome: "Barueri",
      local: "Comercial Alphaville",
      endereco: "Calçada Flor de Lótus, 78",
      observacao: "Comércio",
      coordenadas: {
        longitude: -23.496492,
        latitude: -46.853245,
      },
    },
    {
      regiao: "Sudeste",
      estado: "São Paulo",
      nome: "São Paulo",
      local: "Autovagas - Grand Hyatt",
      endereco: "Avenida das Nações Unidas, 13301",
      observacao: "Hotel",
      coordenadas: {
        longitude: -23.616234,
        latitude: -46.698814,
      },
    },
    {
      regiao: "Sudeste",
      estado: "São Paulo",
      nome: "São Paulo",
      local: "Autovagas - Sala São Paulo",
      endereco: "Praça Júlio Prestes, 16",
      observacao: "Entretenimento",
      coordenadas: {
        longitude: -23.533948,
        latitude: -46.639693,
      },
    },
    {
      regiao: "Sudeste",
      estado: "São Paulo",
      nome: "São Paulo",
      local: "WT Morumbi",
      endereco: "Avenida das Nações Unidas, 14261",
      observacao: "Carregador no Valet",
      coordenadas: {
        longitude: -23.623575,
        latitude: -46.701978,
      },
    },
    {
      regiao: "Sudeste",
      estado: "São Paulo",
      nome: "São Roque",
      local: "Vila Don Patto",
      endereco: "Estrada do vinho, KM 2,5",
      observacao: "Restaurante",
      coordenadas: {
        longitude: -23.563056,
        latitude: -47.134621,
      },
    },
    {
      regiao: "Sul",
      estado: "Paraná",
      nome: "Curitiba",
      local: "4 Points by Sheraton Curitibao",
      endereco: "Av. Sete de Setembro, 4211",
      observacao: "Hotel",
      coordenadas: {
        longitude: -25.442535,
        latitude: -49.279137,
      },
    },
    {
      regiao: "Sul",
      estado: "Paraná",
      nome: "Curitiba",
      local: "Festval Brigadeiro",
      endereco: "R. Bgr. Franco, 641",
      observacao: "Supermercado",
      coordenadas: {
        longitude: -25.427324,
        latitude: -49.284495,
      },
    },
    {
      regiao: "Sul",
      estado: "Paraná",
      nome: "Curitiba",
      local: "Festval Alphaville",
      endereco: "Rua Jaguariaíva, 92",
      observacao: "Nenhuma no Momento",
      coordenadas: {
        longitude: -25.392892,
        latitude: -49.16585,
      },
    },
    {
      regiao: "Sul",
      estado: "Santa Catarina",
      nome: "Florianópolis",
      local: "Costão do Santinho",
      endereco: "Estrada Vereador Onildo Lemos, 25051",
      observacao: "Hotel",
      coordenadas: {
        longitude: -27.464493,
        latitude: -48.381264,
      },
    },
    {
      regiao: "Sul",
      estado: "Santa Catarina",
      nome: "Florianópolis",
      local: "Shopping Beira Mar",
      endereco: "R. Bocaiúva, 2468",
      observacao: "Shopping",
      coordenadas: {
        longitude: -27.584662,
        latitude: -48.544971,
      },
    },
  ],
});
